export const PRODUCT = {
  LOAD: "LOAD_PRODUCT",
  SUCCESS: "LOAD_PRODUCT_SUCCESS",
  ERROR: "LOAD_PRODUCT_ERROR",
  DISPLAY: "SET_DISPLAY-PRODUCT",
  DETAIL: "SET_DETAIL_PRODUCT",
};

export * from "./products/action";
